// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leida = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_leida);
    lv_obj_set_width(ui_leida, 800);
    lv_obj_set_height(ui_leida, 480);
    lv_obj_set_align(ui_leida, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leida, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leida, lv_color_hex(0x120202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leida, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youqianfang = lv_img_create(ui_leida);
    lv_img_set_src(ui_youqianfang, &ui_img_1324262503);
    lv_obj_set_width(ui_youqianfang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_youqianfang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_youqianfang, 65);
    lv_obj_set_y(ui_youqianfang, -160);
    lv_obj_set_align(ui_youqianfang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youqianfang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youqianfang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_youqianfang, 50);
    lv_obj_set_style_opa(ui_youqianfang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoqianfang = lv_img_create(ui_leida);
    lv_img_set_src(ui_zuoqianfang, &ui_img_1324262503);
    lv_obj_set_width(ui_zuoqianfang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zuoqianfang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zuoqianfang, -77);
    lv_obj_set_y(ui_zuoqianfang, -159);
    lv_obj_set_align(ui_zuoqianfang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuoqianfang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuoqianfang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zuoqianfang, 50);
    lv_obj_set_style_opa(ui_zuoqianfang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuohoufang = lv_img_create(ui_leida);
    lv_img_set_src(ui_zuohoufang, &ui_img_1324262503);
    lv_obj_set_width(ui_zuohoufang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zuohoufang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zuohoufang, -80);
    lv_obj_set_y(ui_zuohoufang, 162);
    lv_obj_set_align(ui_zuohoufang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuohoufang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuohoufang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zuohoufang, 50);
    lv_obj_set_style_opa(ui_zuohoufang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youhoufang = lv_img_create(ui_leida);
    lv_img_set_src(ui_youhoufang, &ui_img_1324262503);
    lv_obj_set_width(ui_youhoufang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_youhoufang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_youhoufang, 64);
    lv_obj_set_y(ui_youhoufang, 163);
    lv_obj_set_align(ui_youhoufang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youhoufang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youhoufang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_youhoufang, 50);
    lv_obj_set_style_opa(ui_youhoufang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_car = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_car, &ui_img_group_14_png);
    lv_obj_set_width(ui_car, LV_SIZE_CONTENT);   /// 955
    lv_obj_set_height(ui_car, LV_SIZE_CONTENT);    /// 1122
    lv_obj_set_align(ui_car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_car, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leidamodechange = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_leidamodechange, 75);
    lv_obj_set_height(ui_leidamodechange, 50);
    lv_obj_set_x(ui_leidamodechange, -311);
    lv_obj_set_y(ui_leidamodechange, -165);
    lv_obj_set_align(ui_leidamodechange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leidamodechange, "leida mode");
    lv_obj_set_style_text_color(ui_leidamodechange, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leidamodechange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leidamodechange, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_youqianfang, ui_event_youqianfang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leidamodechange, ui_event_leidamodechange, LV_EVENT_ALL, NULL);
}
