// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// 文件顶部添加
lv_obj_t *ui_licheng_label;
lv_obj_t *ui_wendu_label;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_allcontainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_allcontainer);
    lv_obj_set_width(ui_allcontainer, 800);
    lv_obj_set_height(ui_allcontainer, 480);
    lv_obj_set_align(ui_allcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_allcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_allcontainer, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_allcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topsingle3 = lv_img_create(ui_allcontainer);
    lv_img_set_src(ui_topsingle3, &ui_img_960084724);
    lv_obj_set_width(ui_topsingle3, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_topsingle3, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_topsingle3, 35);
    lv_obj_set_y(ui_topsingle3, -78);
    lv_obj_set_align(ui_topsingle3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_topsingle3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_topsingle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_safesinglecontainer = lv_obj_create(ui_allcontainer);
    lv_obj_remove_style_all(ui_safesinglecontainer);
    lv_obj_set_width(ui_safesinglecontainer, 800);
    lv_obj_set_height(ui_safesinglecontainer, 480);
    lv_obj_set_align(ui_safesinglecontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_safesinglecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_safetybete = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_safetybete, &ui_img_624413955);
    lv_obj_set_width(ui_safetybete, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_safetybete, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_safetybete, -25);
    lv_obj_set_y(ui_safetybete, 32);
    lv_obj_set_align(ui_safetybete, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_safetybete, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_safetybete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_motor = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_motor, &ui_img_457315224);
    lv_obj_set_width(ui_motor, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_motor, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_motor, 45);
    lv_obj_set_y(ui_motor, -42);
    lv_obj_set_align(ui_motor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_motor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_motor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hydraulic = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_hydraulic, &ui_img_1961050311);
    lv_obj_set_width(ui_hydraulic, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_hydraulic, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_hydraulic, -152);
    lv_obj_set_y(ui_hydraulic, 37);
    lv_obj_set_align(ui_hydraulic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hydraulic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hydraulic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oilbox = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_oilbox, &ui_img_525674082);
    lv_obj_set_width(ui_oilbox, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_oilbox, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_oilbox, 306);
    lv_obj_set_y(ui_oilbox, 74);
    lv_obj_set_align(ui_oilbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_oilbox, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_oilbox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftlight = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_leftlight, &ui_img_1119118486);
    lv_obj_set_width(ui_leftlight, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_leftlight, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_leftlight, -236);
    lv_obj_set_y(ui_leftlight, -104);
    lv_obj_set_align(ui_leftlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftlight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leftlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_leftlight, 1800);

    ui_rightlight = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_rightlight, &ui_img_1119118486);
    lv_obj_set_width(ui_rightlight, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_rightlight, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_rightlight, 315);
    lv_obj_set_y(ui_rightlight, -105);
    lv_obj_set_align(ui_rightlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightlight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rightlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_taiyalow = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_taiyalow, &ui_img_165777803);
    lv_obj_set_width(ui_taiyalow, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_taiyalow, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_taiyalow, -336);
    lv_obj_set_y(ui_taiyalow, 182);
    lv_obj_set_align(ui_taiyalow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_taiyalow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_taiyalow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_taiyalow, 50);

    ui_taiyahigh = lv_img_create(ui_safesinglecontainer);
    lv_img_set_src(ui_taiyahigh, &ui_img_151439093);
    lv_obj_set_width(ui_taiyahigh, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_taiyahigh, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_taiyahigh, -337);
    lv_obj_set_y(ui_taiyahigh, 126);
    lv_obj_set_align(ui_taiyahigh, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_taiyahigh, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_taiyahigh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_taiyahigh, 50);

    ui_lightcontainer = lv_obj_create(ui_allcontainer);
    lv_obj_remove_style_all(ui_lightcontainer);
    lv_obj_set_width(ui_lightcontainer, 67);
    lv_obj_set_height(ui_lightcontainer, 99);
    lv_obj_set_x(ui_lightcontainer, -343);
    lv_obj_set_y(ui_lightcontainer, 30);
    lv_obj_set_align(ui_lightcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lightcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_closelight = lv_img_create(ui_lightcontainer);
    lv_img_set_src(ui_closelight, &ui_img_vector_png);
    lv_obj_set_width(ui_closelight, 34);
    lv_obj_set_height(ui_closelight, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_closelight, -1);
    lv_obj_set_y(ui_closelight, -16);
    lv_obj_set_align(ui_closelight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_closelight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_closelight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_farlight = lv_img_create(ui_lightcontainer);
    lv_img_set_src(ui_farlight, &ui_img_314426297);
    lv_obj_set_width(ui_farlight, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_farlight, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_farlight, -1);
    lv_obj_set_y(ui_farlight, 22);
    lv_obj_set_align(ui_farlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_farlight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_farlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_farlight, 50);

    ui_timepanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_timepanel, 292);
    lv_obj_set_height(ui_timepanel, 50);
    lv_obj_set_x(ui_timepanel, 27);
    lv_obj_set_y(ui_timepanel, -195);
    lv_obj_set_align(ui_timepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timepanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timelabel = lv_label_create(ui_timepanel);
    lv_obj_set_width(ui_timelabel, 282);
    lv_obj_set_height(ui_timelabel, 40);
    lv_obj_set_align(ui_timelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timelabel, "");
    lv_obj_set_style_text_font(ui_timelabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yibiaopanpng = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yibiaopanpng, &ui_img_1681097765);
    lv_obj_set_width(ui_yibiaopanpng, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_yibiaopanpng, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_yibiaopanpng, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yibiaopanpng, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yibiaopanpng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bottomsingle1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_bottomsingle1, &ui_img_960096759);
    lv_obj_set_width(ui_bottomsingle1, LV_SIZE_CONTENT);   /// 777
    lv_obj_set_height(ui_bottomsingle1, LV_SIZE_CONTENT);    /// 597
    lv_obj_set_x(ui_bottomsingle1, -39);
    lv_obj_set_y(ui_bottomsingle1, 157);
    lv_obj_set_align(ui_bottomsingle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bottomsingle1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bottomsingle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bottomsingle1, 100);

    ui_bottomsingle2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_bottomsingle2, &ui_img_960091386);
    lv_obj_set_width(ui_bottomsingle2, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_bottomsingle2, LV_SIZE_CONTENT);    /// 97
    lv_obj_set_x(ui_bottomsingle2, -308);
    lv_obj_set_y(ui_bottomsingle2, 216);
    lv_obj_set_align(ui_bottomsingle2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bottomsingle2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bottomsingle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bottomsingle2, 80);

    ui_topsingle1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_topsingle1, &ui_img_414159209);
    lv_obj_set_width(ui_topsingle1, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_topsingle1, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_topsingle1, 304);
    lv_obj_set_y(ui_topsingle1, -193);
    lv_obj_set_align(ui_topsingle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_topsingle1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_topsingle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topsingle2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_topsingle2, &ui_img_414159209);
    lv_obj_set_width(ui_topsingle2, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_topsingle2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_topsingle2, -243);
    lv_obj_set_y(ui_topsingle2, -193);
    lv_obj_set_align(ui_topsingle2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_topsingle2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_topsingle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_topsingle2, 1800);

    ui_speedpoint = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speedpoint, &ui_img_184318935);
    lv_obj_set_width(ui_speedpoint, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_speedpoint, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_speedpoint, 93);
    lv_obj_set_y(ui_speedpoint, 35);
    lv_obj_set_align(ui_speedpoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speedpoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speedpoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_speedpoint, 0, 19);
    lv_img_set_angle(ui_speedpoint, 1380);

    ui_oilpoint = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_oilpoint, &ui_img_2115575519);
    lv_obj_set_width(ui_oilpoint, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_oilpoint, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_oilpoint, 287);
    lv_obj_set_y(ui_oilpoint, 40);
    lv_obj_set_align(ui_oilpoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_oilpoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_oilpoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_oilpoint, 0, 52);
    lv_img_set_angle(ui_oilpoint, 900);

    ui_powerpoint = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_powerpoint, &ui_img_1033847363);
    lv_obj_set_width(ui_powerpoint, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_powerpoint, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_powerpoint, -194);
    lv_obj_set_y(ui_powerpoint, 52);
    lv_obj_set_align(ui_powerpoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_powerpoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_powerpoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_powerpoint, 56, 52);
    lv_img_set_angle(ui_powerpoint, -820);

    ui_licheng = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_licheng, 100);
    lv_obj_set_height(ui_licheng, 26);
    lv_obj_set_x(ui_licheng, 64);
    lv_obj_set_y(ui_licheng, 129);
    lv_obj_set_align(ui_licheng, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_licheng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_licheng, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_licheng, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_licheng, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_licheng, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 在ui_licheng创建后添加标签
    lv_obj_t *ui_licheng_label = lv_label_create(ui_licheng);
    lv_obj_set_width(ui_licheng_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_licheng_label, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_licheng_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_licheng_label, "里程(km): 0");
    lv_obj_set_style_text_color(ui_licheng_label, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_licheng_label, &lv_font_montserrat_14, LV_PART_MAIN);

    ui_wendu = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_wendu, 69);
    lv_obj_set_height(ui_wendu, 25);
    lv_obj_set_x(ui_wendu, -153);
    lv_obj_set_y(ui_wendu, 151);
    lv_obj_set_align(ui_wendu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wendu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wendu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wendu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wendu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wendu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 在ui_wendu创建后添加标签
    lv_obj_t *ui_wendu_label = lv_label_create(ui_wendu);
    lv_obj_set_width(ui_wendu_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_wendu_label, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_wendu_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wendu_label, "温度(°C): 0");
    lv_obj_set_style_text_color(ui_wendu_label, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_wendu_label, &lv_font_montserrat_14, LV_PART_MAIN);

    ui_sportmodechange = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_sportmodechange, 75);
    lv_obj_set_height(ui_sportmodechange, 52);
    lv_obj_set_x(ui_sportmodechange, -344);
    lv_obj_set_y(ui_sportmodechange, -130);
    lv_obj_set_align(ui_sportmodechange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sportmodechange, "sport mode");
    lv_obj_set_style_text_color(ui_sportmodechange, lv_color_hex(0xD6BFC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sportmodechange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sportmodechange, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_closelight, ui_event_closelight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_farlight, ui_event_farlight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sportmodechange, ui_event_sportmodechange, LV_EVENT_ALL, NULL);

}
