// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_luntai = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_luntai);
    lv_obj_set_width(ui_luntai, 800);
    lv_obj_set_height(ui_luntai, 480);
    lv_obj_set_align(ui_luntai, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_luntai, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_luntai, lv_color_hex(0x120202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_luntai, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youqianfang = lv_img_create(ui_luntai);
    lv_img_set_src(ui_youqianfang, &ui_img_1324262503);
    lv_obj_set_width(ui_youqianfang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_youqianfang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_youqianfang, 69);
    lv_obj_set_y(ui_youqianfang, -158);
    lv_obj_set_align(ui_youqianfang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youqianfang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youqianfang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_youqianfang, 50);
    lv_obj_set_style_opa(ui_youqianfang, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoqianfang = lv_img_create(ui_luntai);
    lv_img_set_src(ui_zuoqianfang, &ui_img_1324262503);
    lv_obj_set_width(ui_zuoqianfang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zuoqianfang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zuoqianfang, -81);
    lv_obj_set_y(ui_zuoqianfang, -165);
    lv_obj_set_align(ui_zuoqianfang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuoqianfang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuoqianfang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zuoqianfang, 50);
    lv_obj_set_style_opa(ui_zuoqianfang, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuohoufang = lv_img_create(ui_luntai);
    lv_img_set_src(ui_zuohoufang, &ui_img_1324262503);
    lv_obj_set_width(ui_zuohoufang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zuohoufang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zuohoufang, -80);
    lv_obj_set_y(ui_zuohoufang, 162);
    lv_obj_set_align(ui_zuohoufang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuohoufang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuohoufang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zuohoufang, 50);
    lv_obj_set_style_opa(ui_zuohoufang, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youhoufang = lv_img_create(ui_luntai);
    lv_img_set_src(ui_youhoufang, &ui_img_1324262503);
    lv_obj_set_width(ui_youhoufang, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_youhoufang, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_youhoufang, 69);
    lv_obj_set_y(ui_youhoufang, 169);
    lv_obj_set_align(ui_youhoufang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youhoufang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youhoufang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_youhoufang, 50);
    lv_obj_set_style_opa(ui_youhoufang, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leidamodechange = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_leidamodechange, 75);
    lv_obj_set_height(ui_leidamodechange, 50);
    lv_obj_set_x(ui_leidamodechange, -311);
    lv_obj_set_y(ui_leidamodechange, -165);
    lv_obj_set_align(ui_leidamodechange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leidamodechange, "leida mode");
    lv_obj_set_style_text_color(ui_leidamodechange, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leidamodechange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leidamodechange, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_car = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_car, &ui_img_group_14_png);
    lv_obj_set_width(ui_car, LV_SIZE_CONTENT);   /// 955
    lv_obj_set_height(ui_car, LV_SIZE_CONTENT);    /// 1122
    lv_obj_set_align(ui_car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_car, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_car, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leida = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_leida);
    lv_obj_set_width(ui_leida, 800);
    lv_obj_set_height(ui_leida, 480);
    lv_obj_set_align(ui_leida, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leida, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_youshangld = lv_img_create(ui_leida);
    lv_img_set_src(ui_youshangld, &ui_img_761631266);
    lv_obj_set_width(ui_youshangld, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_youshangld, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_youshangld, 105);
    lv_obj_set_y(ui_youshangld, -197);
    lv_obj_set_align(ui_youshangld, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youshangld, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youshangld, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_youshangld, -300);
    lv_obj_set_style_opa(ui_youshangld, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youxiald = lv_img_create(ui_leida);
    lv_img_set_src(ui_youxiald, &ui_img_761631266);
    lv_obj_set_width(ui_youxiald, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_youxiald, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_youxiald, 84);
    lv_obj_set_y(ui_youxiald, 211);
    lv_obj_set_align(ui_youxiald, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youxiald, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_youxiald, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_youxiald, 300);
    lv_obj_set_style_opa(ui_youxiald, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoxiald = lv_img_create(ui_leida);
    lv_img_set_src(ui_zuoxiald, &ui_img_761631266);
    lv_obj_set_width(ui_zuoxiald, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_zuoxiald, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_zuoxiald, -115);
    lv_obj_set_y(ui_zuoxiald, 204);
    lv_obj_set_align(ui_zuoxiald, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuoxiald, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuoxiald, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_zuoxiald, 1500);
    lv_obj_set_style_opa(ui_zuoxiald, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoshangld = lv_img_create(ui_leida);
    lv_img_set_src(ui_zuoshangld, &ui_img_761631266);
    lv_obj_set_width(ui_zuoshangld, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_zuoshangld, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_zuoshangld, -108);
    lv_obj_set_y(ui_zuoshangld, -196);
    lv_obj_set_align(ui_zuoshangld, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuoshangld, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zuoshangld, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_zuoshangld, -1500);
    lv_obj_set_style_opa(ui_zuoshangld, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_youqianfang, ui_event_youqianfang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zuoqianfang, ui_event_zuoqianfang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zuohoufang, ui_event_zuohoufang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youhoufang, ui_event_youhoufang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leidamodechange, ui_event_leidamodechange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youshangld, ui_event_youshangld, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youxiald, ui_event_youxiald, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zuoxiald, ui_event_zuoxiald, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zuoshangld, ui_event_zuoshangld, LV_EVENT_ALL, NULL);

}
