// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "time.h"
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <pthread.h>

void safesingle_init_gray(void);
void app_state_init(void);
// 正确的事件回调签名（必须接收 lv_event_t* 参数）
void ui_event_sportmodechange(lv_event_t *e);
void ui_event_leidamodechange(lv_event_t *e);
void *input_thread_func(void *arg);
void update_datetime_label(void);
void oilpointanim_Animation(lv_obj_t * TargetObject, int delay);
void speedanim_Animation(lv_obj_t * TargetObject, int delay);
void poweranim_Animation(lv_obj_t * TargetObject, int delay);
void oilboxanim_Animation(lv_obj_t * TargetObject, int delay);
void motoranim_Animation(lv_obj_t * TargetObject, int delay);
void safetybeteanim_Animation(lv_obj_t * TargetObject, int delay);
void hydraulicanim_Animation(lv_obj_t * TargetObject, int delay);
void rightlightanim_Animation(lv_obj_t * TargetObject, int delay);
void leftlightanim_Animation(lv_obj_t * TargetObject, int delay);
void taiyahighlight_Animation(lv_obj_t * TargetObject, int delay);
void taiyalowlight_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_allcontainer;
extern lv_obj_t * ui_topsingle3;
extern lv_obj_t * ui_safesinglecontainer;
extern lv_obj_t * ui_safetybete;
extern lv_obj_t * ui_motor;
extern lv_obj_t * ui_hydraulic;
extern lv_obj_t * ui_oilbox;
extern lv_obj_t * ui_leftlight;
extern lv_obj_t * ui_rightlight;
extern lv_obj_t * ui_taiyalow;
extern lv_obj_t * ui_taiyahigh;
extern lv_obj_t * ui_lightcontainer;
void ui_event_closelight(lv_event_t * e);
extern lv_obj_t * ui_closelight;
void ui_event_farlight(lv_event_t * e);
extern lv_obj_t * ui_farlight;
extern lv_obj_t * ui_timepanel;
extern lv_obj_t * ui_timelabel;
extern lv_obj_t * ui_yibiaopanpng;
extern lv_obj_t * ui_bottomsingle1;
extern lv_obj_t * ui_bottomsingle2;
extern lv_obj_t * ui_topsingle1;
extern lv_obj_t * ui_topsingle2;
extern lv_obj_t * ui_speedpoint;
extern lv_obj_t * ui_oilpoint;
extern lv_obj_t * ui_powerpoint;
extern lv_obj_t * ui_licheng;
extern lv_obj_t * ui_wendu;
void ui_event_sportmodechange(lv_event_t * e);
extern lv_obj_t * ui_sportmodechange;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_leida;
void ui_event_youqianfang(lv_event_t * e);
extern lv_obj_t * ui_youqianfang;
extern lv_obj_t * ui_zuoqianfang;
extern lv_obj_t * ui_zuohoufang;
extern lv_obj_t * ui_youhoufang;
extern lv_obj_t * ui_car;
void ui_event_leidamodechange(lv_event_t * e);
extern lv_obj_t * ui_leidamodechange;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t *ui_licheng_label; 
extern lv_obj_t *ui_wendu_label;


LV_IMG_DECLARE(ui_img_960084724);    // assets/编组 9.png
LV_IMG_DECLARE(ui_img_624413955);    // assets/分组 26.png
LV_IMG_DECLARE(ui_img_457315224);    // assets/分组 27.png
LV_IMG_DECLARE(ui_img_1961050311);    // assets/分组 28.png
LV_IMG_DECLARE(ui_img_525674082);    // assets/分组 29.png
LV_IMG_DECLARE(ui_img_1119118486);    // assets/转向图.png
LV_IMG_DECLARE(ui_img_165777803);    // assets/胎压过低.png
LV_IMG_DECLARE(ui_img_151439093);    // assets/胎压过高.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_314426297);    // assets/远光灯.png
LV_IMG_DECLARE(ui_img_1681097765);    // assets/OBJECTS (3).png
LV_IMG_DECLARE(ui_img_960096759);    // assets/编组 6.png
LV_IMG_DECLARE(ui_img_960091386);    // assets/编组 3.png
LV_IMG_DECLARE(ui_img_414159209);    // assets/编组 7备份 7.png
LV_IMG_DECLARE(ui_img_184318935);    // assets/路径 1598.png
LV_IMG_DECLARE(ui_img_2115575519);    // assets/路径 1600.png
LV_IMG_DECLARE(ui_img_1033847363);    // assets/路径 1611.png
LV_IMG_DECLARE(ui_img_1324262503);    // assets/故障点.png
LV_IMG_DECLARE(ui_img_group_14_png);    // assets/Group 14.png
LV_IMG_DECLARE(ui_img_rectangle_1_png);    // assets/Rectangle 1.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
