// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Calendar2

lv_obj_t * ui_Calendar2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Calendar2;
    cui_Calendar2 = lv_calendar_create(comp_parent);
    lv_calendar_set_today_date(cui_Calendar2, 2025, 8, 26);
    lv_calendar_set_showed_date(cui_Calendar2, 2025, 8);
    lv_obj_t * cui_Calendar2_header = lv_calendar_header_arrow_create(cui_Calendar2);
    lv_obj_set_width(cui_Calendar2, 328);
    lv_obj_set_height(cui_Calendar2, 53);
    lv_obj_set_x(cui_Calendar2, 2);
    lv_obj_set_y(cui_Calendar2, -210);
    lv_obj_set_align(cui_Calendar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Calendar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Calendar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CALENDAR2_NUM);
    children[UI_COMP_CALENDAR2_CALENDAR2] = cui_Calendar2;
    lv_obj_add_event_cb(cui_Calendar2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Calendar2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Calendar2_create_hook(cui_Calendar2);
    return cui_Calendar2;
}

